### ISSUE TITLE
raspbian stretch lite 2018-04-18 freeze

### ISSUE THREAD

**Issue by msantiago** [calcinai/phpi#14]
Hi,
I'm using you're phpi library for more than one year on a raspbian stretch lite 2017-09-07 without any issue, but I just upgrade to the last version of raspbian for the Rpi 3 B+ support and I'm having a big problem !
I can reproduce my issue with the sample websocket application you provide. When I start the server.php sometimes it freezes the Rpi immediately, sometimes I can  access the example at http://raspberrypi.local:9999/ but after playing with the gpio status (output on/off) a few times, it freezes.
I don't know if there are some log files to check to get more informations ...
Thank you for your reply,
Marc-Antoine.

**Comment by calcinai** [comment]
Hi, there aren't any logs produced by phpi itself, but there will be a number of (possibly) useful logs in `/var/log`

Additionally, you could open a second ssh window and run `journalctl -f` while the application is running and you'll see the last log line before the freeze.

Sorry I can't be more help- have you tried it on a fresh install of raspbian, or did you do a kernel upgrade?

**Comment by calcinai** [comment]
Another thought. Are you using the `mmap` extension? You could try with/without depending on what you're already doing.

**Comment by calcinai** [comment]
Hey @msantiago did you make any progress with this?

**Comment by neoteknic** [comment]
Hello, same problem system freeze sometimes, have to hard reboot the rpi 3b+ but no scenario._
Freeze problem on 3b too no log too but I have found freeze with this scenario: 
- use adafruit python script to read dht22 temp hum sensor.
- bind a register press event with phpi (level high trigger). the systeme crash without log.
- php7.2.4 cli with redis ext-event and mmap.

The problem can be with nmap because I never see a php script crashing the OS. Should I try the same but_ without mmap ?
Can you fix the bug ?
of course its stupid to use a port used by another script, it was a mistake but the app shouldn't freeze the os but throw and exeption/warning.

**Comment by calcinai** [comment]
Hey, I think you could be on to something with that python script. It is probably trying to use the same detection register.  Try without the mmap extension and see if that helps?

I can try to make a native driver for the DHT22 for php if that helps.

**Comment by neoteknic** [comment]
I will try without, can you fix mmap to fix system freeze ?
Is it really slow without mmap ?
I don't really need driver for DHT22, I just use an exec process it and output json.
On the RPi B+ I have random system crash, maybe mmap maybe not.
I have disabled it, the subprocess use 2- 4% (average 2.6%) CPU, on the 3B+, it's ok. 
I can depend on events number ?
I can't help to fix mmap because my skills in C++ are not very good. I don't have any log or I din't find it (maybe a system crash dump somewhere?)

**Comment by neoteknic** [comment]
With the subprocess, system freeze again (random), I just a program (websocket, pin event), but I do nothing (no action on pins, jsut some WS call).
The pi didn't freeze without running this.
Can you help me ? Maybe revert to a 3B instead of a 3B+ ?

another problem : start and stop the program with supervisor, and the  python subprocess is still active, I have to manually kill it ? restart /stop and many python subprocess.

**Comment by neoteknic** [comment]
For information : I use an SD image ripped from a pi 3B, I see on the RPI forum that we can do that.
This can cause a problem by using the sd form a 3B with a 3B+ ?
@msantiago Did you use a SD from a 3B in a 3B+ ?

**Comment by neoteknic** [comment]
Ok I progress on the issue : 
Happen in 3b and 3b+ with php 7.1 or 7.2
When a pin event high is triggered, it freeze the rpi no log hard reboot only. It happen with mmap extension and python process.
Can you help me ?

**Comment by calcinai** [comment]
Interesting. Are you running the same kernel version in both installs?

**Comment by calcinai** [comment]
Are you able to share the code you're using so I can try to replicate this?

**Comment by neoteknic** [comment]
Yes same kernel, I just added buster in apt because laravel need php 7.1 +. I can send you a sd image (16go but I can compress it). Or I will make a simple freezing test.
Php 7.1 and 7.2 = freeze.
Note : I use a websocket client in the loop. And redis cache. (php-redis + php-curl added from apt, php-mmap is compiled).

**Comment by neoteknic** [comment]
Maybe change gpio access to /sys/class/gpio, mmaping gpio register is not recommended (and maybe no more python or c mmap ext need) ?

**Comment by calcinai** [comment]
@neoteknic the decision to use `mmap` was deliberate. The `sysfs` based  `/sys/class/gpio` is a lot slower and far more resource intensive.

Is it really not recommended to use the GPIO register? I'd love to read any notes on that out of interest.

All I need to see is the PHP code, I can set up the rest locally.

**Comment by neoteknic** [comment]
Kernel is : Linux raspberrypi 4.14.50-v7+ #1122 SMP Tue Jun 19 12:26:26 BST 2018 armv7l
But there is an update today, I try it, if it crash again I ill send you an example program.

Updated to : 
Linux raspberrypi 4.14.52-v7+ same crash.

**Comment by neoteknic** [comment]
Did you receive my email ?

**Comment by calcinai** [comment]
Hi, I haven't had a chance to test it yet.

**Comment by neoteknic** [comment]
OK, is it fast to make a new branch with /sys/class/gpio to try if it's working ? Can I just change mmap to fopen with this ?

**Comment by calcinai** [comment]
@neoteknic unfortunately not, this library relies on using the registers so it'd be a fairly significant change.  Have a look at the source and you'll see what I mean.  There are also limitations to `sysfs`, so shifting to it would make a lot of the native functionality impossible...

Can I assume that this only occurs when you're adding a listener to an event?  Does it freeze if you just toggle a pin (with an LED, for example)?

Also, can you confirm that nothing else is using the GPIO when your script is?

**Comment by neoteknic** [comment]
Only a script with temp_hum can use a pin with GPIO but it's not used by the program, it crash on a fresh install without this sensor program installed.
I comfirm that toggle an OUPUT pin is working perfectly (set high or low), only events on INPUT ( _$pin->setFunction(PinFunction::INPUT);_ )pin crash the rpi, exactly the once(...) or on(...) I can add an event, but if it's lvl high it instantly triggered and crash the rpi. if all is lvl low, I can bind all, buy when a pin receive a lvl high , it crash the rpi.
I will try to implement something like gpio readall and see if something change to trigger my event maybe (it's not very clean and not reactive (if I check gpio every 1sec), but it can work.

Note my input pin are all (internal) pull_down, I didn't tried it without pull resistor.

**Comment by neoteknic** [comment]
Did you progress on this bug ?
Also I noticed that it's isn't a real "event api (mayby not possible to have real event)" but a 100Hz poll, you should allow to change the poll freq (I need 1hz - 5hz for my app, 100hz is useless for me).
I will build a small event lib with shell_exec('gpio read X') every second or 500ms, it's not very resources intensive (test : 1000 gpio read = 12sec exec time on 3B+).

**Comment by neoteknic** [comment]
New test : 1000 calls with file_get_content('/sys/class/gpio/gpio24') = 0.03sec on B+ (shell_exec much slowed with 12sec ) so it's very fast.
3ms for 100calls so it may be more cpu efficient than mmap (on 3B+ and buster) (0,3% CPU), it's a for test not react loop test, but it's enought.


what are the limitation of sysfs ? you can read, write, pull up /down it's ok for every basic programs, you dont need any php c extension or python script. it's native linux, and can be compatible with all board or pc.

**Comment by calcinai** [comment]
@neoteknic As I'm sure you know, PHP isn't really capable of being "truly" event driven, but that 100Hz poll is checking the _GPEDS_ register, which is what captures events that may have happened in between polls.  For instance, if you `shell_exec('gpio read X')` every second, and there was a pulse for say half a second on the pin, you may miss the rising or falling edge entirely, especially with multiple pulses.

The 100Hz will be more frequent than is required in some cases. You'll see that it's a property with a default (but no setter), so feel free to make a PR with a setter if you'll find this useful.  You'll see a little more of an explanation of this in the code.

As I've mentioned before, `sysfs` does not allow access to any of the native registers, so that would mean that this library wouldn't be able to support some of the more useful features (SPI, I2C, PWM, True edge detection), but if it suits you better, by all means don't let me stop you using it.  Python is shipped by default on Raspbian, so I didn't see it being a barrier to entry here.  The C extension does exactly the same thing as the subprocess, except is much faster (I got it up to over 60KHz on a Pi 3B running PHP7).  This makes soft-pwm realistic on any pin.

I appreciate your help reporting this issue, although I still haven't been able to replicate it. In the mean time, see if you can isolate the actual line of code that triggers the issue.  I was thinking it might be [this line](https://github.com/calcinai/phpi/blob/master/src/PHPi/Pin/EdgeDetector/StatusPoll.php#L156)

It'd be great if we could keep this issue about the actual issue here, rather than a discussion as to why this library doesn't use `sysfs`, it's making it hard to track he progress.  Feel free to start another issue with this discussion if you'd like to propose an alternative to direct register access.

**Comment by mauroak** [comment]
Hi @calcinai, I'm having same issue with, tested on Rpi 3 B+ with/without mmap ext with same reault, always on php7.1 and raspbian strech. My code just do following to get status change on a pin.

```
        $pin = $this->board->getPin($this->getPin())
            ->setFunction(PinFunction::INPUT)
            ->setPull(Pin::PULL_UP);

        $pin->on(Pin::EVENT_LEVEL_CHANGE, function ($level) {
            var_dump($level);
        });

        $this->loop->run();
```

This instantly crashes the pi and force me to do a hard reset. I think its same issue reported here. 

If I do following, it doesn't happen

```
        $pin = $this->board->getPin($this->getPin())
            ->setFunction(PinFunction::INPUT)
            ->setPull(Pin::PULL_UP);

        $loop->addPeriodicTimer($time = 0.01, function() use($pin, $time){
            var_dump($pin->getLevel());
        });

        $this->loop->run();
```

This looks like something related to pulling frequency. Is it possible to overwrite default frecuency in order to avoid this? In my case as @neoteknic 100hz is a lot higher than required for use case. 

Thanks!
Mauro

**Comment by calcinai** [comment]
It looks like it's specifically related to the edge detect register, if you look into the code, it's not really doing what your second snippet is.

Since this was reported, I've actually found some other weird inconsistencies.  I've [asked a question](https://raspberrypi.stackexchange.com/questions/89121/clearing-edge-detect-registers-gparen-gpafen-crashes-raspbian-stretch) on SO so we'll see what happens there!

**Comment by mauroak** [comment]
Thanks @calcinai !! let's see wait to see what SO folks say about it.

**Comment by msantiago** [comment]
Hi, after a long break, I'm back with this issue.
I'm not a Raspberry expert and I can't investigate more than you've ever done.
Do you finally found a solution or a workaround to get it work without freezing ? I just need to be able to trigger a button pressed event.
Thanks a lot for your help !

**Comment by calcinai** [comment]
Hi @msantiago are  you running the same version of stretch? I haven't seen this issue for a while now..

**Comment by msantiago** [comment]
Hi @calcinai,
I've juste done an apt-get dist upgrade and I still have the same issue.

Here is my configuration :

PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"
NAME="Raspbian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

Linux version 4.14.98-v7+ (dom@dom-XPS-13-9370) (gcc version 4.9.3 (crosstool-NG crosstool-ng-1.22.0-88-g8460611)) #1200 SMP Tue Feb 12 20:27:48 GMT 2019

**Comment by calcinai** [comment]
@msantiago @mauroak 

An answer :tada:

Adding `dtoverlay=gpio-no-irq` to /boot/config.txt fixes it.

Previously the kernel would automatically disable interrupts when you set one of rising/falling edge detection methods but that apparently stopped happening, causing a kernel panic.

I'll do a bit more testing then update and release.

Seems to be the same thing that was happening [here](https://raspberrypi.stackexchange.com/questions/103543/pi-locking-up-trying-to-use-rising-falling-edge-detection)

**Comment by justinmespel** [comment]
@calcinai You're a legend, thanks for that! It worked straight away after a reboot! 🎉

**Comment by calcinai** [comment]
@Ravage32 I'll make the code check for that flag to save others the pain!

**Comment by mauroak** [comment]
Hi @calcinai thanks for your help!! it worked like a charm :) I'm resuming my iot project now thanks to you!
